/* 
 * Che Feature API
 *
 * Che Feature API
 *
 * API version: 1.0.0
 * Contact: skabashniuk@redhat.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CheServiceReference struct {

	Name string `json:"name"`

	Version string `json:"version"`

	Services []CheServiceParameter `json:"services,omitempty"`
}
