/* 
 * Che Feature API
 *
 * Che Feature API
 *
 * API version: 1.0.0
 * Contact: skabashniuk@redhat.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PluginLicense struct {

	// License key
	Key string `json:"key"`

	// License Name
	Name string `json:"name"`

	// License url
	Url string `json:"url"`
}
