/* 
 * Che Feature API
 *
 * Che Feature API
 *
 * API version: 1.0.0
 * Contact: skabashniuk@redhat.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PluginOwner struct {

	// Plugin owner
	Name string `json:"name"`

	// Owner awatar url
	AvatarUrl string `json:"avatar_url,omitempty"`

	// Owner gravatar id
	GravatarId string `json:"gravatar_id,omitempty"`

	// Owner url
	Url string `json:"url,omitempty"`
}
