/* 
 * Che Feature API
 *
 * Che Feature API
 *
 * API version: 1.0.0
 * Contact: skabashniuk@redhat.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Server struct {

	Name string `json:"name"`

	Port int32 `json:"port"`

	Protocol string `json:"protocol"`

	Attributes map[string]string `json:"attributes,omitempty"`
}
